
name: Semgrep SAST

on: push

jobs:
  semgrep-sast:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Juice Shop source
        uses: actions/checkout@v4
      - name: Run Semgrep SAST scan
        run: semgrep scan --config=p/default --config=p/javascript --config=p/security-audit .
